dist:
  name: otelcol-hydrolix
  description: Hydrolix OpenTelemetry Collector
  output_path: .

exporters:
  - gomod: github.com/hydrolix/hydrolix-exporter/hydrolixexporter v1.0.0
    path: ./hydrolixexporter
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.141.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.141.0