dist:
  name: otelcol-hydrolix
  description: Hydrolix OpenTelemetry Collector
  output_path: ./dist

exporters:
  - gomod: github.com/hydrolix/hydrolix-exporter v0.0.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.91.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.91.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.91.0

replaces:
  - github.com/hydrolix/hydrolix-exporter v0.0.1 => ./hydrolixexporter