name: on-pull-request-validate
on: pull_request
jobs:
  demo:
    # Hydrolix hosted runner
    runs-on: lke
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
      - name: demo
        run: echo "Hello world"
